import { UserStatus, execute_functions } from "./pkg/rust_module.js";
import type { AppFunctions } from "./pkg/rust_module.js";

let readyMsg = "";
let dataValue = 0;
let dataArray = new Uint8Array(0);
let optionVal: string | undefined = "";
let statusVal: UserStatus | undefined = undefined;

const functions: AppFunctions = {
  onReady: (msg: string) => {
    readyMsg = msg;
  },
  onData: (a: number, b: Uint8Array) => {
    dataValue = a;
    dataArray = new Uint8Array(b); // Clone it so types match strict Uint8Array
  },
  onOption: (val: string | undefined) => {
    optionVal = val;
  },
  onCalculate: (a: number) => {
    return a * 2;
  },
  onStatus: (status: UserStatus) => {
    statusVal = status;
  },
};

// If tsc compiles this without errors, we know that the type
// aliases generated by ts-function match what ts-macro expects in IAppFunctions!
execute_functions(functions);

if (readyMsg !== "System is ready") {
  throw new Error(`Expected "System is ready", got "${readyMsg}"`);
}

if (dataValue !== 42.5) {
  throw new Error(`Expected 42.5, got ${dataValue}`);
}

if (
  dataArray.length !== 3 ||
  dataArray[0] !== 1 ||
  dataArray[1] !== 2 ||
  dataArray[2] !== 3
) {
  throw new Error(`Expected Uint8Array([1, 2, 3]), got ${dataArray}`);
}

if (optionVal !== "present") {
  throw new Error(`Expected "present", got "${optionVal}"`);
}

if (statusVal !== UserStatus.Active) {
  throw new Error(`Expected UserStatus.Active, got ${statusVal}`);
}

console.log(
  "All TS integration tests passed! The generated TypeScript definitions match.",
);
